[package]
name = "luapack"
license = "MPLv2"
version = "0.1.1"
edition = "2024"
categories = ["compression", "encoding"]
keywords = ["pack", "bundle", "minify", "lua"]
repository = "https://github.com/repetitive-contrarian/luapack/tree/master"
description = "A basic rust application for efficiently bundling Lua scripts into monolithic releases."

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
full_moon = { version = "2.0.0", features = ["luau", "cfxlua"] }
lz4_flex = { version = "0.12.0", optional = true}
regex = "1.12.2"

[features]
default = ["lz4"]
dynamic = [] # Enables support for dynamic requires at the cost of heavy compression losses, unless lz4 is used.
lazy = [] # Cache module return values if available, can improve the performance of packed projects by a slight margin but can also cause issues.
lz4 = ["dep:lz4_flex"] # Adds an -l argument that compresses the packed file using the lz4 algorithm, might give you some pretry sweet size improvements if your env supports it. This is kinda bring your own decompressor so use the banner feature to add one if your env doesn't provide one already.